"""Fix model relationships and add foreign keys

Revision ID: 430c058d3a44
Revises: 82707d0248c6
Create Date: 2025-08-23 14:53:51.901247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430c058d3a44'
down_revision = '82707d0248c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
